/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnprotectedRouteRouteImport } from './routes/_unprotected/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedLmsRouteRouteImport } from './routes/_protected/lms/route'
import { Route as ProtectedAdminPanelRouteRouteImport } from './routes/_protected/admin-panel/route'
import { Route as UnprotectedLoginIndexRouteImport } from './routes/_unprotected/login/index'
import { Route as ProtectedLmsIndexRouteImport } from './routes/_protected/lms/index'
import { Route as ProtectedLmsGradesIndexRouteImport } from './routes/_protected/lms/grades/index'
import { Route as ProtectedLmsDashboardIndexRouteImport } from './routes/_protected/lms/dashboard/index'
import { Route as ProtectedLmsClassesIndexRouteImport } from './routes/_protected/lms/classes/index'
import { Route as ProtectedAdminPanelStudentsIndexRouteImport } from './routes/_protected/admin-panel/students/index'
import { Route as ProtectedAdminPanelSemestersIndexRouteImport } from './routes/_protected/admin-panel/semesters/index'
import { Route as ProtectedAdminPanelSectionsIndexRouteImport } from './routes/_protected/admin-panel/sections/index'
import { Route as ProtectedAdminPanelProgramsIndexRouteImport } from './routes/_protected/admin-panel/programs/index'
import { Route as ProtectedAdminPanelInstructorsIndexRouteImport } from './routes/_protected/admin-panel/instructors/index'
import { Route as ProtectedAdminPanelDepartmentsIndexRouteImport } from './routes/_protected/admin-panel/departments/index'
import { Route as ProtectedAdminPanelDashboardIndexRouteImport } from './routes/_protected/admin-panel/dashboard/index'
import { Route as ProtectedAdminPanelCoursesIndexRouteImport } from './routes/_protected/admin-panel/courses/index'
import { Route as ProtectedAdminPanelClassesIndexRouteImport } from './routes/_protected/admin-panel/classes/index'
import { Route as ProtectedAdminPanelAdminsIndexRouteImport } from './routes/_protected/admin-panel/admins/index'
import { Route as ProtectedAdminPanelStudentsStudentIdRouteRouteImport } from './routes/_protected/admin-panel/students/$studentId/route'
import { Route as ProtectedAdminPanelInstructorsInstructorIdRouteRouteImport } from './routes/_protected/admin-panel/instructors/$instructorId/route'
import { Route as ProtectedAdminPanelStudentsCreateIndexRouteImport } from './routes/_protected/admin-panel/students/create/index'
import { Route as ProtectedAdminPanelStudentsStudentIdIndexRouteImport } from './routes/_protected/admin-panel/students/$studentId/index'
import { Route as ProtectedAdminPanelSemestersCreateIndexRouteImport } from './routes/_protected/admin-panel/semesters/create/index'
import { Route as ProtectedAdminPanelSectionsCreateIndexRouteImport } from './routes/_protected/admin-panel/sections/create/index'
import { Route as ProtectedAdminPanelSectionsSectionIdIndexRouteImport } from './routes/_protected/admin-panel/sections/$sectionId/index'
import { Route as ProtectedAdminPanelProgramsCreateIndexRouteImport } from './routes/_protected/admin-panel/programs/create/index'
import { Route as ProtectedAdminPanelInstructorsCreateIndexRouteImport } from './routes/_protected/admin-panel/instructors/create/index'
import { Route as ProtectedAdminPanelInstructorsInstructorIdIndexRouteImport } from './routes/_protected/admin-panel/instructors/$instructorId/index'
import { Route as ProtectedAdminPanelDepartmentsCreateIndexRouteImport } from './routes/_protected/admin-panel/departments/create/index'
import { Route as ProtectedAdminPanelCoursesCreateIndexRouteImport } from './routes/_protected/admin-panel/courses/create/index'
import { Route as ProtectedAdminPanelClassesCreateIndexRouteImport } from './routes/_protected/admin-panel/classes/create/index'
import { Route as ProtectedAdminPanelAdminsCreateIndexRouteImport } from './routes/_protected/admin-panel/admins/create/index'
import { Route as ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRouteImport } from './routes/_protected/admin-panel/students/$studentId_/enroll-to-class/index'
import { Route as ProtectedAdminPanelStudentsStudentIdEditIndexRouteImport } from './routes/_protected/admin-panel/students/$studentId_/edit/index'
import { Route as ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRouteImport } from './routes/_protected/admin-panel/students/$studentId/enrolled-classes/index'
import { Route as ProtectedAdminPanelSectionsSectionIdEditIndexRouteImport } from './routes/_protected/admin-panel/sections/$sectionId/edit/index'
import { Route as ProtectedAdminPanelProgramsProgramIdEditIndexRouteImport } from './routes/_protected/admin-panel/programs/$programId/edit/index'
import { Route as ProtectedAdminPanelInstructorsInstructorIdEditIndexRouteImport } from './routes/_protected/admin-panel/instructors/$instructorId_/edit/index'
import { Route as ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRouteImport } from './routes/_protected/admin-panel/instructors/$instructorId_/assign-to-class/index'
import { Route as ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRouteImport } from './routes/_protected/admin-panel/instructors/$instructorId/assigned-classes/index'
import { Route as ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRouteImport } from './routes/_protected/admin-panel/departments/$departmentId/edit/index'
import { Route as ProtectedAdminPanelCoursesCourseIdEditIndexRouteImport } from './routes/_protected/admin-panel/courses/$courseId/edit/index'
import { Route as ProtectedAdminPanelClassesClassIdEditIndexRouteImport } from './routes/_protected/admin-panel/classes/$classId/edit/index'
import { Route as ProtectedAdminPanelAdminsAdminIdEditIndexRouteImport } from './routes/_protected/admin-panel/admins/$adminId/edit/index'

const UnprotectedRouteRoute = UnprotectedRouteRouteImport.update({
  id: '/_unprotected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLmsRouteRoute = ProtectedLmsRouteRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminPanelRouteRoute =
  ProtectedAdminPanelRouteRouteImport.update({
    id: '/admin-panel',
    path: '/admin-panel',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const UnprotectedLoginIndexRoute = UnprotectedLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => UnprotectedRouteRoute,
} as any)
const ProtectedLmsIndexRoute = ProtectedLmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedLmsRouteRoute,
} as any)
const ProtectedLmsGradesIndexRoute = ProtectedLmsGradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => ProtectedLmsRouteRoute,
} as any)
const ProtectedLmsDashboardIndexRoute =
  ProtectedLmsDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedLmsRouteRoute,
  } as any)
const ProtectedLmsClassesIndexRoute =
  ProtectedLmsClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => ProtectedLmsRouteRoute,
  } as any)
const ProtectedAdminPanelStudentsIndexRoute =
  ProtectedAdminPanelStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelSemestersIndexRoute =
  ProtectedAdminPanelSemestersIndexRouteImport.update({
    id: '/semesters/',
    path: '/semesters/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelSectionsIndexRoute =
  ProtectedAdminPanelSectionsIndexRouteImport.update({
    id: '/sections/',
    path: '/sections/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelProgramsIndexRoute =
  ProtectedAdminPanelProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelInstructorsIndexRoute =
  ProtectedAdminPanelInstructorsIndexRouteImport.update({
    id: '/instructors/',
    path: '/instructors/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelDepartmentsIndexRoute =
  ProtectedAdminPanelDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelDashboardIndexRoute =
  ProtectedAdminPanelDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelCoursesIndexRoute =
  ProtectedAdminPanelCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelClassesIndexRoute =
  ProtectedAdminPanelClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelAdminsIndexRoute =
  ProtectedAdminPanelAdminsIndexRouteImport.update({
    id: '/admins/',
    path: '/admins/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelStudentsStudentIdRouteRoute =
  ProtectedAdminPanelStudentsStudentIdRouteRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelInstructorsInstructorIdRouteRoute =
  ProtectedAdminPanelInstructorsInstructorIdRouteRouteImport.update({
    id: '/instructors/$instructorId',
    path: '/instructors/$instructorId',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelStudentsCreateIndexRoute =
  ProtectedAdminPanelStudentsCreateIndexRouteImport.update({
    id: '/students/create/',
    path: '/students/create/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelStudentsStudentIdIndexRoute =
  ProtectedAdminPanelStudentsStudentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdminPanelStudentsStudentIdRouteRoute,
  } as any)
const ProtectedAdminPanelSemestersCreateIndexRoute =
  ProtectedAdminPanelSemestersCreateIndexRouteImport.update({
    id: '/semesters/create/',
    path: '/semesters/create/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelSectionsCreateIndexRoute =
  ProtectedAdminPanelSectionsCreateIndexRouteImport.update({
    id: '/sections/create/',
    path: '/sections/create/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelSectionsSectionIdIndexRoute =
  ProtectedAdminPanelSectionsSectionIdIndexRouteImport.update({
    id: '/sections/$sectionId/',
    path: '/sections/$sectionId/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelProgramsCreateIndexRoute =
  ProtectedAdminPanelProgramsCreateIndexRouteImport.update({
    id: '/programs/create/',
    path: '/programs/create/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelInstructorsCreateIndexRoute =
  ProtectedAdminPanelInstructorsCreateIndexRouteImport.update({
    id: '/instructors/create/',
    path: '/instructors/create/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelInstructorsInstructorIdIndexRoute =
  ProtectedAdminPanelInstructorsInstructorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdminPanelInstructorsInstructorIdRouteRoute,
  } as any)
const ProtectedAdminPanelDepartmentsCreateIndexRoute =
  ProtectedAdminPanelDepartmentsCreateIndexRouteImport.update({
    id: '/departments/create/',
    path: '/departments/create/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelCoursesCreateIndexRoute =
  ProtectedAdminPanelCoursesCreateIndexRouteImport.update({
    id: '/courses/create/',
    path: '/courses/create/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelClassesCreateIndexRoute =
  ProtectedAdminPanelClassesCreateIndexRouteImport.update({
    id: '/classes/create/',
    path: '/classes/create/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelAdminsCreateIndexRoute =
  ProtectedAdminPanelAdminsCreateIndexRouteImport.update({
    id: '/admins/create/',
    path: '/admins/create/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRoute =
  ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRouteImport.update({
    id: '/students/$studentId_/enroll-to-class/',
    path: '/students/$studentId/enroll-to-class/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelStudentsStudentIdEditIndexRoute =
  ProtectedAdminPanelStudentsStudentIdEditIndexRouteImport.update({
    id: '/students/$studentId_/edit/',
    path: '/students/$studentId/edit/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRoute =
  ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRouteImport.update({
    id: '/enrolled-classes/',
    path: '/enrolled-classes/',
    getParentRoute: () => ProtectedAdminPanelStudentsStudentIdRouteRoute,
  } as any)
const ProtectedAdminPanelSectionsSectionIdEditIndexRoute =
  ProtectedAdminPanelSectionsSectionIdEditIndexRouteImport.update({
    id: '/sections/$sectionId/edit/',
    path: '/sections/$sectionId/edit/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelProgramsProgramIdEditIndexRoute =
  ProtectedAdminPanelProgramsProgramIdEditIndexRouteImport.update({
    id: '/programs/$programId/edit/',
    path: '/programs/$programId/edit/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelInstructorsInstructorIdEditIndexRoute =
  ProtectedAdminPanelInstructorsInstructorIdEditIndexRouteImport.update({
    id: '/instructors/$instructorId_/edit/',
    path: '/instructors/$instructorId/edit/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRoute =
  ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRouteImport.update(
    {
      id: '/instructors/$instructorId_/assign-to-class/',
      path: '/instructors/$instructorId/assign-to-class/',
      getParentRoute: () => ProtectedAdminPanelRouteRoute,
    } as any,
  )
const ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRoute =
  ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRouteImport.update(
    {
      id: '/assigned-classes/',
      path: '/assigned-classes/',
      getParentRoute: () =>
        ProtectedAdminPanelInstructorsInstructorIdRouteRoute,
    } as any,
  )
const ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRoute =
  ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRouteImport.update({
    id: '/departments/$departmentId/edit/',
    path: '/departments/$departmentId/edit/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelCoursesCourseIdEditIndexRoute =
  ProtectedAdminPanelCoursesCourseIdEditIndexRouteImport.update({
    id: '/courses/$courseId/edit/',
    path: '/courses/$courseId/edit/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelClassesClassIdEditIndexRoute =
  ProtectedAdminPanelClassesClassIdEditIndexRouteImport.update({
    id: '/classes/$classId/edit/',
    path: '/classes/$classId/edit/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)
const ProtectedAdminPanelAdminsAdminIdEditIndexRoute =
  ProtectedAdminPanelAdminsAdminIdEditIndexRouteImport.update({
    id: '/admins/$adminId/edit/',
    path: '/admins/$adminId/edit/',
    getParentRoute: () => ProtectedAdminPanelRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-panel': typeof ProtectedAdminPanelRouteRouteWithChildren
  '/lms': typeof ProtectedLmsRouteRouteWithChildren
  '/lms/': typeof ProtectedLmsIndexRoute
  '/login': typeof UnprotectedLoginIndexRoute
  '/admin-panel/instructors/$instructorId': typeof ProtectedAdminPanelInstructorsInstructorIdRouteRouteWithChildren
  '/admin-panel/students/$studentId': typeof ProtectedAdminPanelStudentsStudentIdRouteRouteWithChildren
  '/admin-panel/admins': typeof ProtectedAdminPanelAdminsIndexRoute
  '/admin-panel/classes': typeof ProtectedAdminPanelClassesIndexRoute
  '/admin-panel/courses': typeof ProtectedAdminPanelCoursesIndexRoute
  '/admin-panel/dashboard': typeof ProtectedAdminPanelDashboardIndexRoute
  '/admin-panel/departments': typeof ProtectedAdminPanelDepartmentsIndexRoute
  '/admin-panel/instructors': typeof ProtectedAdminPanelInstructorsIndexRoute
  '/admin-panel/programs': typeof ProtectedAdminPanelProgramsIndexRoute
  '/admin-panel/sections': typeof ProtectedAdminPanelSectionsIndexRoute
  '/admin-panel/semesters': typeof ProtectedAdminPanelSemestersIndexRoute
  '/admin-panel/students': typeof ProtectedAdminPanelStudentsIndexRoute
  '/lms/classes': typeof ProtectedLmsClassesIndexRoute
  '/lms/dashboard': typeof ProtectedLmsDashboardIndexRoute
  '/lms/grades': typeof ProtectedLmsGradesIndexRoute
  '/admin-panel/admins/create': typeof ProtectedAdminPanelAdminsCreateIndexRoute
  '/admin-panel/classes/create': typeof ProtectedAdminPanelClassesCreateIndexRoute
  '/admin-panel/courses/create': typeof ProtectedAdminPanelCoursesCreateIndexRoute
  '/admin-panel/departments/create': typeof ProtectedAdminPanelDepartmentsCreateIndexRoute
  '/admin-panel/instructors/$instructorId/': typeof ProtectedAdminPanelInstructorsInstructorIdIndexRoute
  '/admin-panel/instructors/create': typeof ProtectedAdminPanelInstructorsCreateIndexRoute
  '/admin-panel/programs/create': typeof ProtectedAdminPanelProgramsCreateIndexRoute
  '/admin-panel/sections/$sectionId': typeof ProtectedAdminPanelSectionsSectionIdIndexRoute
  '/admin-panel/sections/create': typeof ProtectedAdminPanelSectionsCreateIndexRoute
  '/admin-panel/semesters/create': typeof ProtectedAdminPanelSemestersCreateIndexRoute
  '/admin-panel/students/$studentId/': typeof ProtectedAdminPanelStudentsStudentIdIndexRoute
  '/admin-panel/students/create': typeof ProtectedAdminPanelStudentsCreateIndexRoute
  '/admin-panel/admins/$adminId/edit': typeof ProtectedAdminPanelAdminsAdminIdEditIndexRoute
  '/admin-panel/classes/$classId/edit': typeof ProtectedAdminPanelClassesClassIdEditIndexRoute
  '/admin-panel/courses/$courseId/edit': typeof ProtectedAdminPanelCoursesCourseIdEditIndexRoute
  '/admin-panel/departments/$departmentId/edit': typeof ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRoute
  '/admin-panel/instructors/$instructorId/assigned-classes': typeof ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRoute
  '/admin-panel/instructors/$instructorId/assign-to-class': typeof ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRoute
  '/admin-panel/instructors/$instructorId/edit': typeof ProtectedAdminPanelInstructorsInstructorIdEditIndexRoute
  '/admin-panel/programs/$programId/edit': typeof ProtectedAdminPanelProgramsProgramIdEditIndexRoute
  '/admin-panel/sections/$sectionId/edit': typeof ProtectedAdminPanelSectionsSectionIdEditIndexRoute
  '/admin-panel/students/$studentId/enrolled-classes': typeof ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRoute
  '/admin-panel/students/$studentId/edit': typeof ProtectedAdminPanelStudentsStudentIdEditIndexRoute
  '/admin-panel/students/$studentId/enroll-to-class': typeof ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-panel': typeof ProtectedAdminPanelRouteRouteWithChildren
  '/lms': typeof ProtectedLmsIndexRoute
  '/login': typeof UnprotectedLoginIndexRoute
  '/admin-panel/admins': typeof ProtectedAdminPanelAdminsIndexRoute
  '/admin-panel/classes': typeof ProtectedAdminPanelClassesIndexRoute
  '/admin-panel/courses': typeof ProtectedAdminPanelCoursesIndexRoute
  '/admin-panel/dashboard': typeof ProtectedAdminPanelDashboardIndexRoute
  '/admin-panel/departments': typeof ProtectedAdminPanelDepartmentsIndexRoute
  '/admin-panel/instructors': typeof ProtectedAdminPanelInstructorsIndexRoute
  '/admin-panel/programs': typeof ProtectedAdminPanelProgramsIndexRoute
  '/admin-panel/sections': typeof ProtectedAdminPanelSectionsIndexRoute
  '/admin-panel/semesters': typeof ProtectedAdminPanelSemestersIndexRoute
  '/admin-panel/students': typeof ProtectedAdminPanelStudentsIndexRoute
  '/lms/classes': typeof ProtectedLmsClassesIndexRoute
  '/lms/dashboard': typeof ProtectedLmsDashboardIndexRoute
  '/lms/grades': typeof ProtectedLmsGradesIndexRoute
  '/admin-panel/admins/create': typeof ProtectedAdminPanelAdminsCreateIndexRoute
  '/admin-panel/classes/create': typeof ProtectedAdminPanelClassesCreateIndexRoute
  '/admin-panel/courses/create': typeof ProtectedAdminPanelCoursesCreateIndexRoute
  '/admin-panel/departments/create': typeof ProtectedAdminPanelDepartmentsCreateIndexRoute
  '/admin-panel/instructors/$instructorId': typeof ProtectedAdminPanelInstructorsInstructorIdIndexRoute
  '/admin-panel/instructors/create': typeof ProtectedAdminPanelInstructorsCreateIndexRoute
  '/admin-panel/programs/create': typeof ProtectedAdminPanelProgramsCreateIndexRoute
  '/admin-panel/sections/$sectionId': typeof ProtectedAdminPanelSectionsSectionIdIndexRoute
  '/admin-panel/sections/create': typeof ProtectedAdminPanelSectionsCreateIndexRoute
  '/admin-panel/semesters/create': typeof ProtectedAdminPanelSemestersCreateIndexRoute
  '/admin-panel/students/$studentId': typeof ProtectedAdminPanelStudentsStudentIdIndexRoute
  '/admin-panel/students/create': typeof ProtectedAdminPanelStudentsCreateIndexRoute
  '/admin-panel/admins/$adminId/edit': typeof ProtectedAdminPanelAdminsAdminIdEditIndexRoute
  '/admin-panel/classes/$classId/edit': typeof ProtectedAdminPanelClassesClassIdEditIndexRoute
  '/admin-panel/courses/$courseId/edit': typeof ProtectedAdminPanelCoursesCourseIdEditIndexRoute
  '/admin-panel/departments/$departmentId/edit': typeof ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRoute
  '/admin-panel/instructors/$instructorId/assigned-classes': typeof ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRoute
  '/admin-panel/instructors/$instructorId/assign-to-class': typeof ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRoute
  '/admin-panel/instructors/$instructorId/edit': typeof ProtectedAdminPanelInstructorsInstructorIdEditIndexRoute
  '/admin-panel/programs/$programId/edit': typeof ProtectedAdminPanelProgramsProgramIdEditIndexRoute
  '/admin-panel/sections/$sectionId/edit': typeof ProtectedAdminPanelSectionsSectionIdEditIndexRoute
  '/admin-panel/students/$studentId/enrolled-classes': typeof ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRoute
  '/admin-panel/students/$studentId/edit': typeof ProtectedAdminPanelStudentsStudentIdEditIndexRoute
  '/admin-panel/students/$studentId/enroll-to-class': typeof ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_unprotected': typeof UnprotectedRouteRouteWithChildren
  '/_protected/admin-panel': typeof ProtectedAdminPanelRouteRouteWithChildren
  '/_protected/lms': typeof ProtectedLmsRouteRouteWithChildren
  '/_protected/lms/': typeof ProtectedLmsIndexRoute
  '/_unprotected/login/': typeof UnprotectedLoginIndexRoute
  '/_protected/admin-panel/instructors/$instructorId': typeof ProtectedAdminPanelInstructorsInstructorIdRouteRouteWithChildren
  '/_protected/admin-panel/students/$studentId': typeof ProtectedAdminPanelStudentsStudentIdRouteRouteWithChildren
  '/_protected/admin-panel/admins/': typeof ProtectedAdminPanelAdminsIndexRoute
  '/_protected/admin-panel/classes/': typeof ProtectedAdminPanelClassesIndexRoute
  '/_protected/admin-panel/courses/': typeof ProtectedAdminPanelCoursesIndexRoute
  '/_protected/admin-panel/dashboard/': typeof ProtectedAdminPanelDashboardIndexRoute
  '/_protected/admin-panel/departments/': typeof ProtectedAdminPanelDepartmentsIndexRoute
  '/_protected/admin-panel/instructors/': typeof ProtectedAdminPanelInstructorsIndexRoute
  '/_protected/admin-panel/programs/': typeof ProtectedAdminPanelProgramsIndexRoute
  '/_protected/admin-panel/sections/': typeof ProtectedAdminPanelSectionsIndexRoute
  '/_protected/admin-panel/semesters/': typeof ProtectedAdminPanelSemestersIndexRoute
  '/_protected/admin-panel/students/': typeof ProtectedAdminPanelStudentsIndexRoute
  '/_protected/lms/classes/': typeof ProtectedLmsClassesIndexRoute
  '/_protected/lms/dashboard/': typeof ProtectedLmsDashboardIndexRoute
  '/_protected/lms/grades/': typeof ProtectedLmsGradesIndexRoute
  '/_protected/admin-panel/admins/create/': typeof ProtectedAdminPanelAdminsCreateIndexRoute
  '/_protected/admin-panel/classes/create/': typeof ProtectedAdminPanelClassesCreateIndexRoute
  '/_protected/admin-panel/courses/create/': typeof ProtectedAdminPanelCoursesCreateIndexRoute
  '/_protected/admin-panel/departments/create/': typeof ProtectedAdminPanelDepartmentsCreateIndexRoute
  '/_protected/admin-panel/instructors/$instructorId/': typeof ProtectedAdminPanelInstructorsInstructorIdIndexRoute
  '/_protected/admin-panel/instructors/create/': typeof ProtectedAdminPanelInstructorsCreateIndexRoute
  '/_protected/admin-panel/programs/create/': typeof ProtectedAdminPanelProgramsCreateIndexRoute
  '/_protected/admin-panel/sections/$sectionId/': typeof ProtectedAdminPanelSectionsSectionIdIndexRoute
  '/_protected/admin-panel/sections/create/': typeof ProtectedAdminPanelSectionsCreateIndexRoute
  '/_protected/admin-panel/semesters/create/': typeof ProtectedAdminPanelSemestersCreateIndexRoute
  '/_protected/admin-panel/students/$studentId/': typeof ProtectedAdminPanelStudentsStudentIdIndexRoute
  '/_protected/admin-panel/students/create/': typeof ProtectedAdminPanelStudentsCreateIndexRoute
  '/_protected/admin-panel/admins/$adminId/edit/': typeof ProtectedAdminPanelAdminsAdminIdEditIndexRoute
  '/_protected/admin-panel/classes/$classId/edit/': typeof ProtectedAdminPanelClassesClassIdEditIndexRoute
  '/_protected/admin-panel/courses/$courseId/edit/': typeof ProtectedAdminPanelCoursesCourseIdEditIndexRoute
  '/_protected/admin-panel/departments/$departmentId/edit/': typeof ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRoute
  '/_protected/admin-panel/instructors/$instructorId/assigned-classes/': typeof ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRoute
  '/_protected/admin-panel/instructors/$instructorId_/assign-to-class/': typeof ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRoute
  '/_protected/admin-panel/instructors/$instructorId_/edit/': typeof ProtectedAdminPanelInstructorsInstructorIdEditIndexRoute
  '/_protected/admin-panel/programs/$programId/edit/': typeof ProtectedAdminPanelProgramsProgramIdEditIndexRoute
  '/_protected/admin-panel/sections/$sectionId/edit/': typeof ProtectedAdminPanelSectionsSectionIdEditIndexRoute
  '/_protected/admin-panel/students/$studentId/enrolled-classes/': typeof ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRoute
  '/_protected/admin-panel/students/$studentId_/edit/': typeof ProtectedAdminPanelStudentsStudentIdEditIndexRoute
  '/_protected/admin-panel/students/$studentId_/enroll-to-class/': typeof ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-panel'
    | '/lms'
    | '/lms/'
    | '/login'
    | '/admin-panel/instructors/$instructorId'
    | '/admin-panel/students/$studentId'
    | '/admin-panel/admins'
    | '/admin-panel/classes'
    | '/admin-panel/courses'
    | '/admin-panel/dashboard'
    | '/admin-panel/departments'
    | '/admin-panel/instructors'
    | '/admin-panel/programs'
    | '/admin-panel/sections'
    | '/admin-panel/semesters'
    | '/admin-panel/students'
    | '/lms/classes'
    | '/lms/dashboard'
    | '/lms/grades'
    | '/admin-panel/admins/create'
    | '/admin-panel/classes/create'
    | '/admin-panel/courses/create'
    | '/admin-panel/departments/create'
    | '/admin-panel/instructors/$instructorId/'
    | '/admin-panel/instructors/create'
    | '/admin-panel/programs/create'
    | '/admin-panel/sections/$sectionId'
    | '/admin-panel/sections/create'
    | '/admin-panel/semesters/create'
    | '/admin-panel/students/$studentId/'
    | '/admin-panel/students/create'
    | '/admin-panel/admins/$adminId/edit'
    | '/admin-panel/classes/$classId/edit'
    | '/admin-panel/courses/$courseId/edit'
    | '/admin-panel/departments/$departmentId/edit'
    | '/admin-panel/instructors/$instructorId/assigned-classes'
    | '/admin-panel/instructors/$instructorId/assign-to-class'
    | '/admin-panel/instructors/$instructorId/edit'
    | '/admin-panel/programs/$programId/edit'
    | '/admin-panel/sections/$sectionId/edit'
    | '/admin-panel/students/$studentId/enrolled-classes'
    | '/admin-panel/students/$studentId/edit'
    | '/admin-panel/students/$studentId/enroll-to-class'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-panel'
    | '/lms'
    | '/login'
    | '/admin-panel/admins'
    | '/admin-panel/classes'
    | '/admin-panel/courses'
    | '/admin-panel/dashboard'
    | '/admin-panel/departments'
    | '/admin-panel/instructors'
    | '/admin-panel/programs'
    | '/admin-panel/sections'
    | '/admin-panel/semesters'
    | '/admin-panel/students'
    | '/lms/classes'
    | '/lms/dashboard'
    | '/lms/grades'
    | '/admin-panel/admins/create'
    | '/admin-panel/classes/create'
    | '/admin-panel/courses/create'
    | '/admin-panel/departments/create'
    | '/admin-panel/instructors/$instructorId'
    | '/admin-panel/instructors/create'
    | '/admin-panel/programs/create'
    | '/admin-panel/sections/$sectionId'
    | '/admin-panel/sections/create'
    | '/admin-panel/semesters/create'
    | '/admin-panel/students/$studentId'
    | '/admin-panel/students/create'
    | '/admin-panel/admins/$adminId/edit'
    | '/admin-panel/classes/$classId/edit'
    | '/admin-panel/courses/$courseId/edit'
    | '/admin-panel/departments/$departmentId/edit'
    | '/admin-panel/instructors/$instructorId/assigned-classes'
    | '/admin-panel/instructors/$instructorId/assign-to-class'
    | '/admin-panel/instructors/$instructorId/edit'
    | '/admin-panel/programs/$programId/edit'
    | '/admin-panel/sections/$sectionId/edit'
    | '/admin-panel/students/$studentId/enrolled-classes'
    | '/admin-panel/students/$studentId/edit'
    | '/admin-panel/students/$studentId/enroll-to-class'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_unprotected'
    | '/_protected/admin-panel'
    | '/_protected/lms'
    | '/_protected/lms/'
    | '/_unprotected/login/'
    | '/_protected/admin-panel/instructors/$instructorId'
    | '/_protected/admin-panel/students/$studentId'
    | '/_protected/admin-panel/admins/'
    | '/_protected/admin-panel/classes/'
    | '/_protected/admin-panel/courses/'
    | '/_protected/admin-panel/dashboard/'
    | '/_protected/admin-panel/departments/'
    | '/_protected/admin-panel/instructors/'
    | '/_protected/admin-panel/programs/'
    | '/_protected/admin-panel/sections/'
    | '/_protected/admin-panel/semesters/'
    | '/_protected/admin-panel/students/'
    | '/_protected/lms/classes/'
    | '/_protected/lms/dashboard/'
    | '/_protected/lms/grades/'
    | '/_protected/admin-panel/admins/create/'
    | '/_protected/admin-panel/classes/create/'
    | '/_protected/admin-panel/courses/create/'
    | '/_protected/admin-panel/departments/create/'
    | '/_protected/admin-panel/instructors/$instructorId/'
    | '/_protected/admin-panel/instructors/create/'
    | '/_protected/admin-panel/programs/create/'
    | '/_protected/admin-panel/sections/$sectionId/'
    | '/_protected/admin-panel/sections/create/'
    | '/_protected/admin-panel/semesters/create/'
    | '/_protected/admin-panel/students/$studentId/'
    | '/_protected/admin-panel/students/create/'
    | '/_protected/admin-panel/admins/$adminId/edit/'
    | '/_protected/admin-panel/classes/$classId/edit/'
    | '/_protected/admin-panel/courses/$courseId/edit/'
    | '/_protected/admin-panel/departments/$departmentId/edit/'
    | '/_protected/admin-panel/instructors/$instructorId/assigned-classes/'
    | '/_protected/admin-panel/instructors/$instructorId_/assign-to-class/'
    | '/_protected/admin-panel/instructors/$instructorId_/edit/'
    | '/_protected/admin-panel/programs/$programId/edit/'
    | '/_protected/admin-panel/sections/$sectionId/edit/'
    | '/_protected/admin-panel/students/$studentId/enrolled-classes/'
    | '/_protected/admin-panel/students/$studentId_/edit/'
    | '/_protected/admin-panel/students/$studentId_/enroll-to-class/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  UnprotectedRouteRoute: typeof UnprotectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unprotected': {
      id: '/_unprotected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnprotectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/lms': {
      id: '/_protected/lms'
      path: '/lms'
      fullPath: '/lms'
      preLoaderRoute: typeof ProtectedLmsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin-panel': {
      id: '/_protected/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof ProtectedAdminPanelRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_unprotected/login/': {
      id: '/_unprotected/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnprotectedLoginIndexRouteImport
      parentRoute: typeof UnprotectedRouteRoute
    }
    '/_protected/lms/': {
      id: '/_protected/lms/'
      path: '/'
      fullPath: '/lms/'
      preLoaderRoute: typeof ProtectedLmsIndexRouteImport
      parentRoute: typeof ProtectedLmsRouteRoute
    }
    '/_protected/lms/grades/': {
      id: '/_protected/lms/grades/'
      path: '/grades'
      fullPath: '/lms/grades'
      preLoaderRoute: typeof ProtectedLmsGradesIndexRouteImport
      parentRoute: typeof ProtectedLmsRouteRoute
    }
    '/_protected/lms/dashboard/': {
      id: '/_protected/lms/dashboard/'
      path: '/dashboard'
      fullPath: '/lms/dashboard'
      preLoaderRoute: typeof ProtectedLmsDashboardIndexRouteImport
      parentRoute: typeof ProtectedLmsRouteRoute
    }
    '/_protected/lms/classes/': {
      id: '/_protected/lms/classes/'
      path: '/classes'
      fullPath: '/lms/classes'
      preLoaderRoute: typeof ProtectedLmsClassesIndexRouteImport
      parentRoute: typeof ProtectedLmsRouteRoute
    }
    '/_protected/admin-panel/students/': {
      id: '/_protected/admin-panel/students/'
      path: '/students'
      fullPath: '/admin-panel/students'
      preLoaderRoute: typeof ProtectedAdminPanelStudentsIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/semesters/': {
      id: '/_protected/admin-panel/semesters/'
      path: '/semesters'
      fullPath: '/admin-panel/semesters'
      preLoaderRoute: typeof ProtectedAdminPanelSemestersIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/sections/': {
      id: '/_protected/admin-panel/sections/'
      path: '/sections'
      fullPath: '/admin-panel/sections'
      preLoaderRoute: typeof ProtectedAdminPanelSectionsIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/programs/': {
      id: '/_protected/admin-panel/programs/'
      path: '/programs'
      fullPath: '/admin-panel/programs'
      preLoaderRoute: typeof ProtectedAdminPanelProgramsIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/instructors/': {
      id: '/_protected/admin-panel/instructors/'
      path: '/instructors'
      fullPath: '/admin-panel/instructors'
      preLoaderRoute: typeof ProtectedAdminPanelInstructorsIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/departments/': {
      id: '/_protected/admin-panel/departments/'
      path: '/departments'
      fullPath: '/admin-panel/departments'
      preLoaderRoute: typeof ProtectedAdminPanelDepartmentsIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/dashboard/': {
      id: '/_protected/admin-panel/dashboard/'
      path: '/dashboard'
      fullPath: '/admin-panel/dashboard'
      preLoaderRoute: typeof ProtectedAdminPanelDashboardIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/courses/': {
      id: '/_protected/admin-panel/courses/'
      path: '/courses'
      fullPath: '/admin-panel/courses'
      preLoaderRoute: typeof ProtectedAdminPanelCoursesIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/classes/': {
      id: '/_protected/admin-panel/classes/'
      path: '/classes'
      fullPath: '/admin-panel/classes'
      preLoaderRoute: typeof ProtectedAdminPanelClassesIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/admins/': {
      id: '/_protected/admin-panel/admins/'
      path: '/admins'
      fullPath: '/admin-panel/admins'
      preLoaderRoute: typeof ProtectedAdminPanelAdminsIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/students/$studentId': {
      id: '/_protected/admin-panel/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/admin-panel/students/$studentId'
      preLoaderRoute: typeof ProtectedAdminPanelStudentsStudentIdRouteRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/instructors/$instructorId': {
      id: '/_protected/admin-panel/instructors/$instructorId'
      path: '/instructors/$instructorId'
      fullPath: '/admin-panel/instructors/$instructorId'
      preLoaderRoute: typeof ProtectedAdminPanelInstructorsInstructorIdRouteRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/students/create/': {
      id: '/_protected/admin-panel/students/create/'
      path: '/students/create'
      fullPath: '/admin-panel/students/create'
      preLoaderRoute: typeof ProtectedAdminPanelStudentsCreateIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/students/$studentId/': {
      id: '/_protected/admin-panel/students/$studentId/'
      path: '/'
      fullPath: '/admin-panel/students/$studentId/'
      preLoaderRoute: typeof ProtectedAdminPanelStudentsStudentIdIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelStudentsStudentIdRouteRoute
    }
    '/_protected/admin-panel/semesters/create/': {
      id: '/_protected/admin-panel/semesters/create/'
      path: '/semesters/create'
      fullPath: '/admin-panel/semesters/create'
      preLoaderRoute: typeof ProtectedAdminPanelSemestersCreateIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/sections/create/': {
      id: '/_protected/admin-panel/sections/create/'
      path: '/sections/create'
      fullPath: '/admin-panel/sections/create'
      preLoaderRoute: typeof ProtectedAdminPanelSectionsCreateIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/sections/$sectionId/': {
      id: '/_protected/admin-panel/sections/$sectionId/'
      path: '/sections/$sectionId'
      fullPath: '/admin-panel/sections/$sectionId'
      preLoaderRoute: typeof ProtectedAdminPanelSectionsSectionIdIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/programs/create/': {
      id: '/_protected/admin-panel/programs/create/'
      path: '/programs/create'
      fullPath: '/admin-panel/programs/create'
      preLoaderRoute: typeof ProtectedAdminPanelProgramsCreateIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/instructors/create/': {
      id: '/_protected/admin-panel/instructors/create/'
      path: '/instructors/create'
      fullPath: '/admin-panel/instructors/create'
      preLoaderRoute: typeof ProtectedAdminPanelInstructorsCreateIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/instructors/$instructorId/': {
      id: '/_protected/admin-panel/instructors/$instructorId/'
      path: '/'
      fullPath: '/admin-panel/instructors/$instructorId/'
      preLoaderRoute: typeof ProtectedAdminPanelInstructorsInstructorIdIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelInstructorsInstructorIdRouteRoute
    }
    '/_protected/admin-panel/departments/create/': {
      id: '/_protected/admin-panel/departments/create/'
      path: '/departments/create'
      fullPath: '/admin-panel/departments/create'
      preLoaderRoute: typeof ProtectedAdminPanelDepartmentsCreateIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/courses/create/': {
      id: '/_protected/admin-panel/courses/create/'
      path: '/courses/create'
      fullPath: '/admin-panel/courses/create'
      preLoaderRoute: typeof ProtectedAdminPanelCoursesCreateIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/classes/create/': {
      id: '/_protected/admin-panel/classes/create/'
      path: '/classes/create'
      fullPath: '/admin-panel/classes/create'
      preLoaderRoute: typeof ProtectedAdminPanelClassesCreateIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/admins/create/': {
      id: '/_protected/admin-panel/admins/create/'
      path: '/admins/create'
      fullPath: '/admin-panel/admins/create'
      preLoaderRoute: typeof ProtectedAdminPanelAdminsCreateIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/students/$studentId_/enroll-to-class/': {
      id: '/_protected/admin-panel/students/$studentId_/enroll-to-class/'
      path: '/students/$studentId/enroll-to-class'
      fullPath: '/admin-panel/students/$studentId/enroll-to-class'
      preLoaderRoute: typeof ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/students/$studentId_/edit/': {
      id: '/_protected/admin-panel/students/$studentId_/edit/'
      path: '/students/$studentId/edit'
      fullPath: '/admin-panel/students/$studentId/edit'
      preLoaderRoute: typeof ProtectedAdminPanelStudentsStudentIdEditIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/students/$studentId/enrolled-classes/': {
      id: '/_protected/admin-panel/students/$studentId/enrolled-classes/'
      path: '/enrolled-classes'
      fullPath: '/admin-panel/students/$studentId/enrolled-classes'
      preLoaderRoute: typeof ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelStudentsStudentIdRouteRoute
    }
    '/_protected/admin-panel/sections/$sectionId/edit/': {
      id: '/_protected/admin-panel/sections/$sectionId/edit/'
      path: '/sections/$sectionId/edit'
      fullPath: '/admin-panel/sections/$sectionId/edit'
      preLoaderRoute: typeof ProtectedAdminPanelSectionsSectionIdEditIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/programs/$programId/edit/': {
      id: '/_protected/admin-panel/programs/$programId/edit/'
      path: '/programs/$programId/edit'
      fullPath: '/admin-panel/programs/$programId/edit'
      preLoaderRoute: typeof ProtectedAdminPanelProgramsProgramIdEditIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/instructors/$instructorId_/edit/': {
      id: '/_protected/admin-panel/instructors/$instructorId_/edit/'
      path: '/instructors/$instructorId/edit'
      fullPath: '/admin-panel/instructors/$instructorId/edit'
      preLoaderRoute: typeof ProtectedAdminPanelInstructorsInstructorIdEditIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/instructors/$instructorId_/assign-to-class/': {
      id: '/_protected/admin-panel/instructors/$instructorId_/assign-to-class/'
      path: '/instructors/$instructorId/assign-to-class'
      fullPath: '/admin-panel/instructors/$instructorId/assign-to-class'
      preLoaderRoute: typeof ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/instructors/$instructorId/assigned-classes/': {
      id: '/_protected/admin-panel/instructors/$instructorId/assigned-classes/'
      path: '/assigned-classes'
      fullPath: '/admin-panel/instructors/$instructorId/assigned-classes'
      preLoaderRoute: typeof ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelInstructorsInstructorIdRouteRoute
    }
    '/_protected/admin-panel/departments/$departmentId/edit/': {
      id: '/_protected/admin-panel/departments/$departmentId/edit/'
      path: '/departments/$departmentId/edit'
      fullPath: '/admin-panel/departments/$departmentId/edit'
      preLoaderRoute: typeof ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/courses/$courseId/edit/': {
      id: '/_protected/admin-panel/courses/$courseId/edit/'
      path: '/courses/$courseId/edit'
      fullPath: '/admin-panel/courses/$courseId/edit'
      preLoaderRoute: typeof ProtectedAdminPanelCoursesCourseIdEditIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/classes/$classId/edit/': {
      id: '/_protected/admin-panel/classes/$classId/edit/'
      path: '/classes/$classId/edit'
      fullPath: '/admin-panel/classes/$classId/edit'
      preLoaderRoute: typeof ProtectedAdminPanelClassesClassIdEditIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
    '/_protected/admin-panel/admins/$adminId/edit/': {
      id: '/_protected/admin-panel/admins/$adminId/edit/'
      path: '/admins/$adminId/edit'
      fullPath: '/admin-panel/admins/$adminId/edit'
      preLoaderRoute: typeof ProtectedAdminPanelAdminsAdminIdEditIndexRouteImport
      parentRoute: typeof ProtectedAdminPanelRouteRoute
    }
  }
}

interface ProtectedAdminPanelInstructorsInstructorIdRouteRouteChildren {
  ProtectedAdminPanelInstructorsInstructorIdIndexRoute: typeof ProtectedAdminPanelInstructorsInstructorIdIndexRoute
  ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRoute: typeof ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRoute
}

const ProtectedAdminPanelInstructorsInstructorIdRouteRouteChildren: ProtectedAdminPanelInstructorsInstructorIdRouteRouteChildren =
  {
    ProtectedAdminPanelInstructorsInstructorIdIndexRoute:
      ProtectedAdminPanelInstructorsInstructorIdIndexRoute,
    ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRoute:
      ProtectedAdminPanelInstructorsInstructorIdAssignedClassesIndexRoute,
  }

const ProtectedAdminPanelInstructorsInstructorIdRouteRouteWithChildren =
  ProtectedAdminPanelInstructorsInstructorIdRouteRoute._addFileChildren(
    ProtectedAdminPanelInstructorsInstructorIdRouteRouteChildren,
  )

interface ProtectedAdminPanelStudentsStudentIdRouteRouteChildren {
  ProtectedAdminPanelStudentsStudentIdIndexRoute: typeof ProtectedAdminPanelStudentsStudentIdIndexRoute
  ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRoute: typeof ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRoute
}

const ProtectedAdminPanelStudentsStudentIdRouteRouteChildren: ProtectedAdminPanelStudentsStudentIdRouteRouteChildren =
  {
    ProtectedAdminPanelStudentsStudentIdIndexRoute:
      ProtectedAdminPanelStudentsStudentIdIndexRoute,
    ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRoute:
      ProtectedAdminPanelStudentsStudentIdEnrolledClassesIndexRoute,
  }

const ProtectedAdminPanelStudentsStudentIdRouteRouteWithChildren =
  ProtectedAdminPanelStudentsStudentIdRouteRoute._addFileChildren(
    ProtectedAdminPanelStudentsStudentIdRouteRouteChildren,
  )

interface ProtectedAdminPanelRouteRouteChildren {
  ProtectedAdminPanelInstructorsInstructorIdRouteRoute: typeof ProtectedAdminPanelInstructorsInstructorIdRouteRouteWithChildren
  ProtectedAdminPanelStudentsStudentIdRouteRoute: typeof ProtectedAdminPanelStudentsStudentIdRouteRouteWithChildren
  ProtectedAdminPanelAdminsIndexRoute: typeof ProtectedAdminPanelAdminsIndexRoute
  ProtectedAdminPanelClassesIndexRoute: typeof ProtectedAdminPanelClassesIndexRoute
  ProtectedAdminPanelCoursesIndexRoute: typeof ProtectedAdminPanelCoursesIndexRoute
  ProtectedAdminPanelDashboardIndexRoute: typeof ProtectedAdminPanelDashboardIndexRoute
  ProtectedAdminPanelDepartmentsIndexRoute: typeof ProtectedAdminPanelDepartmentsIndexRoute
  ProtectedAdminPanelInstructorsIndexRoute: typeof ProtectedAdminPanelInstructorsIndexRoute
  ProtectedAdminPanelProgramsIndexRoute: typeof ProtectedAdminPanelProgramsIndexRoute
  ProtectedAdminPanelSectionsIndexRoute: typeof ProtectedAdminPanelSectionsIndexRoute
  ProtectedAdminPanelSemestersIndexRoute: typeof ProtectedAdminPanelSemestersIndexRoute
  ProtectedAdminPanelStudentsIndexRoute: typeof ProtectedAdminPanelStudentsIndexRoute
  ProtectedAdminPanelAdminsCreateIndexRoute: typeof ProtectedAdminPanelAdminsCreateIndexRoute
  ProtectedAdminPanelClassesCreateIndexRoute: typeof ProtectedAdminPanelClassesCreateIndexRoute
  ProtectedAdminPanelCoursesCreateIndexRoute: typeof ProtectedAdminPanelCoursesCreateIndexRoute
  ProtectedAdminPanelDepartmentsCreateIndexRoute: typeof ProtectedAdminPanelDepartmentsCreateIndexRoute
  ProtectedAdminPanelInstructorsCreateIndexRoute: typeof ProtectedAdminPanelInstructorsCreateIndexRoute
  ProtectedAdminPanelProgramsCreateIndexRoute: typeof ProtectedAdminPanelProgramsCreateIndexRoute
  ProtectedAdminPanelSectionsSectionIdIndexRoute: typeof ProtectedAdminPanelSectionsSectionIdIndexRoute
  ProtectedAdminPanelSectionsCreateIndexRoute: typeof ProtectedAdminPanelSectionsCreateIndexRoute
  ProtectedAdminPanelSemestersCreateIndexRoute: typeof ProtectedAdminPanelSemestersCreateIndexRoute
  ProtectedAdminPanelStudentsCreateIndexRoute: typeof ProtectedAdminPanelStudentsCreateIndexRoute
  ProtectedAdminPanelAdminsAdminIdEditIndexRoute: typeof ProtectedAdminPanelAdminsAdminIdEditIndexRoute
  ProtectedAdminPanelClassesClassIdEditIndexRoute: typeof ProtectedAdminPanelClassesClassIdEditIndexRoute
  ProtectedAdminPanelCoursesCourseIdEditIndexRoute: typeof ProtectedAdminPanelCoursesCourseIdEditIndexRoute
  ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRoute: typeof ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRoute
  ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRoute: typeof ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRoute
  ProtectedAdminPanelInstructorsInstructorIdEditIndexRoute: typeof ProtectedAdminPanelInstructorsInstructorIdEditIndexRoute
  ProtectedAdminPanelProgramsProgramIdEditIndexRoute: typeof ProtectedAdminPanelProgramsProgramIdEditIndexRoute
  ProtectedAdminPanelSectionsSectionIdEditIndexRoute: typeof ProtectedAdminPanelSectionsSectionIdEditIndexRoute
  ProtectedAdminPanelStudentsStudentIdEditIndexRoute: typeof ProtectedAdminPanelStudentsStudentIdEditIndexRoute
  ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRoute: typeof ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRoute
}

const ProtectedAdminPanelRouteRouteChildren: ProtectedAdminPanelRouteRouteChildren =
  {
    ProtectedAdminPanelInstructorsInstructorIdRouteRoute:
      ProtectedAdminPanelInstructorsInstructorIdRouteRouteWithChildren,
    ProtectedAdminPanelStudentsStudentIdRouteRoute:
      ProtectedAdminPanelStudentsStudentIdRouteRouteWithChildren,
    ProtectedAdminPanelAdminsIndexRoute: ProtectedAdminPanelAdminsIndexRoute,
    ProtectedAdminPanelClassesIndexRoute: ProtectedAdminPanelClassesIndexRoute,
    ProtectedAdminPanelCoursesIndexRoute: ProtectedAdminPanelCoursesIndexRoute,
    ProtectedAdminPanelDashboardIndexRoute:
      ProtectedAdminPanelDashboardIndexRoute,
    ProtectedAdminPanelDepartmentsIndexRoute:
      ProtectedAdminPanelDepartmentsIndexRoute,
    ProtectedAdminPanelInstructorsIndexRoute:
      ProtectedAdminPanelInstructorsIndexRoute,
    ProtectedAdminPanelProgramsIndexRoute:
      ProtectedAdminPanelProgramsIndexRoute,
    ProtectedAdminPanelSectionsIndexRoute:
      ProtectedAdminPanelSectionsIndexRoute,
    ProtectedAdminPanelSemestersIndexRoute:
      ProtectedAdminPanelSemestersIndexRoute,
    ProtectedAdminPanelStudentsIndexRoute:
      ProtectedAdminPanelStudentsIndexRoute,
    ProtectedAdminPanelAdminsCreateIndexRoute:
      ProtectedAdminPanelAdminsCreateIndexRoute,
    ProtectedAdminPanelClassesCreateIndexRoute:
      ProtectedAdminPanelClassesCreateIndexRoute,
    ProtectedAdminPanelCoursesCreateIndexRoute:
      ProtectedAdminPanelCoursesCreateIndexRoute,
    ProtectedAdminPanelDepartmentsCreateIndexRoute:
      ProtectedAdminPanelDepartmentsCreateIndexRoute,
    ProtectedAdminPanelInstructorsCreateIndexRoute:
      ProtectedAdminPanelInstructorsCreateIndexRoute,
    ProtectedAdminPanelProgramsCreateIndexRoute:
      ProtectedAdminPanelProgramsCreateIndexRoute,
    ProtectedAdminPanelSectionsSectionIdIndexRoute:
      ProtectedAdminPanelSectionsSectionIdIndexRoute,
    ProtectedAdminPanelSectionsCreateIndexRoute:
      ProtectedAdminPanelSectionsCreateIndexRoute,
    ProtectedAdminPanelSemestersCreateIndexRoute:
      ProtectedAdminPanelSemestersCreateIndexRoute,
    ProtectedAdminPanelStudentsCreateIndexRoute:
      ProtectedAdminPanelStudentsCreateIndexRoute,
    ProtectedAdminPanelAdminsAdminIdEditIndexRoute:
      ProtectedAdminPanelAdminsAdminIdEditIndexRoute,
    ProtectedAdminPanelClassesClassIdEditIndexRoute:
      ProtectedAdminPanelClassesClassIdEditIndexRoute,
    ProtectedAdminPanelCoursesCourseIdEditIndexRoute:
      ProtectedAdminPanelCoursesCourseIdEditIndexRoute,
    ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRoute:
      ProtectedAdminPanelDepartmentsDepartmentIdEditIndexRoute,
    ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRoute:
      ProtectedAdminPanelInstructorsInstructorIdAssignToClassIndexRoute,
    ProtectedAdminPanelInstructorsInstructorIdEditIndexRoute:
      ProtectedAdminPanelInstructorsInstructorIdEditIndexRoute,
    ProtectedAdminPanelProgramsProgramIdEditIndexRoute:
      ProtectedAdminPanelProgramsProgramIdEditIndexRoute,
    ProtectedAdminPanelSectionsSectionIdEditIndexRoute:
      ProtectedAdminPanelSectionsSectionIdEditIndexRoute,
    ProtectedAdminPanelStudentsStudentIdEditIndexRoute:
      ProtectedAdminPanelStudentsStudentIdEditIndexRoute,
    ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRoute:
      ProtectedAdminPanelStudentsStudentIdEnrollToClassIndexRoute,
  }

const ProtectedAdminPanelRouteRouteWithChildren =
  ProtectedAdminPanelRouteRoute._addFileChildren(
    ProtectedAdminPanelRouteRouteChildren,
  )

interface ProtectedLmsRouteRouteChildren {
  ProtectedLmsIndexRoute: typeof ProtectedLmsIndexRoute
  ProtectedLmsClassesIndexRoute: typeof ProtectedLmsClassesIndexRoute
  ProtectedLmsDashboardIndexRoute: typeof ProtectedLmsDashboardIndexRoute
  ProtectedLmsGradesIndexRoute: typeof ProtectedLmsGradesIndexRoute
}

const ProtectedLmsRouteRouteChildren: ProtectedLmsRouteRouteChildren = {
  ProtectedLmsIndexRoute: ProtectedLmsIndexRoute,
  ProtectedLmsClassesIndexRoute: ProtectedLmsClassesIndexRoute,
  ProtectedLmsDashboardIndexRoute: ProtectedLmsDashboardIndexRoute,
  ProtectedLmsGradesIndexRoute: ProtectedLmsGradesIndexRoute,
}

const ProtectedLmsRouteRouteWithChildren =
  ProtectedLmsRouteRoute._addFileChildren(ProtectedLmsRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedAdminPanelRouteRoute: typeof ProtectedAdminPanelRouteRouteWithChildren
  ProtectedLmsRouteRoute: typeof ProtectedLmsRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminPanelRouteRoute: ProtectedAdminPanelRouteRouteWithChildren,
  ProtectedLmsRouteRoute: ProtectedLmsRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface UnprotectedRouteRouteChildren {
  UnprotectedLoginIndexRoute: typeof UnprotectedLoginIndexRoute
}

const UnprotectedRouteRouteChildren: UnprotectedRouteRouteChildren = {
  UnprotectedLoginIndexRoute: UnprotectedLoginIndexRoute,
}

const UnprotectedRouteRouteWithChildren =
  UnprotectedRouteRoute._addFileChildren(UnprotectedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  UnprotectedRouteRoute: UnprotectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
