/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnprotectedRouteRouteImport } from './routes/_unprotected/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnprotectedLoginIndexRouteImport } from './routes/_unprotected/login/index'
import { Route as ProtectedStudentsIndexRouteImport } from './routes/_protected/students/index'
import { Route as ProtectedSemestersIndexRouteImport } from './routes/_protected/semesters/index'
import { Route as ProtectedSectionsIndexRouteImport } from './routes/_protected/sections/index'
import { Route as ProtectedProgramsIndexRouteImport } from './routes/_protected/programs/index'
import { Route as ProtectedInstructorsIndexRouteImport } from './routes/_protected/instructors/index'
import { Route as ProtectedDepartmentsIndexRouteImport } from './routes/_protected/departments/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedCoursesIndexRouteImport } from './routes/_protected/courses/index'
import { Route as ProtectedClassesIndexRouteImport } from './routes/_protected/classes/index'
import { Route as ProtectedAdminsIndexRouteImport } from './routes/_protected/admins/index'
import { Route as ProtectedStudentsStudentIdRouteRouteImport } from './routes/_protected/students/$studentId/route'
import { Route as ProtectedInstructorsInstructorIdRouteRouteImport } from './routes/_protected/instructors/$instructorId/route'
import { Route as ProtectedStudentsCreateIndexRouteImport } from './routes/_protected/students/create/index'
import { Route as ProtectedStudentsStudentIdIndexRouteImport } from './routes/_protected/students/$studentId/index'
import { Route as ProtectedSemestersCreateIndexRouteImport } from './routes/_protected/semesters/create/index'
import { Route as ProtectedSectionsCreateIndexRouteImport } from './routes/_protected/sections/create/index'
import { Route as ProtectedSectionsSectionIdIndexRouteImport } from './routes/_protected/sections/$sectionId/index'
import { Route as ProtectedProgramsCreateIndexRouteImport } from './routes/_protected/programs/create/index'
import { Route as ProtectedInstructorsCreateIndexRouteImport } from './routes/_protected/instructors/create/index'
import { Route as ProtectedInstructorsInstructorIdIndexRouteImport } from './routes/_protected/instructors/$instructorId/index'
import { Route as ProtectedDepartmentsCreateIndexRouteImport } from './routes/_protected/departments/create/index'
import { Route as ProtectedCoursesCreateIndexRouteImport } from './routes/_protected/courses/create/index'
import { Route as ProtectedClassesCreateIndexRouteImport } from './routes/_protected/classes/create/index'
import { Route as ProtectedAdminsCreateIndexRouteImport } from './routes/_protected/admins/create/index'
import { Route as ProtectedStudentsStudentIdEnrollToClassIndexRouteImport } from './routes/_protected/students/$studentId_/enroll-to-class/index'
import { Route as ProtectedStudentsStudentIdEditIndexRouteImport } from './routes/_protected/students/$studentId_/edit/index'
import { Route as ProtectedStudentsStudentIdEnrolledClassesIndexRouteImport } from './routes/_protected/students/$studentId/enrolled-classes/index'
import { Route as ProtectedSectionsSectionIdEditIndexRouteImport } from './routes/_protected/sections/$sectionId/edit/index'
import { Route as ProtectedProgramsProgramIdEditIndexRouteImport } from './routes/_protected/programs/$programId/edit/index'
import { Route as ProtectedInstructorsInstructorIdEditIndexRouteImport } from './routes/_protected/instructors/$instructorId_/edit/index'
import { Route as ProtectedInstructorsInstructorIdAssignToClassIndexRouteImport } from './routes/_protected/instructors/$instructorId_/assign-to-class/index'
import { Route as ProtectedInstructorsInstructorIdAssignedClassesIndexRouteImport } from './routes/_protected/instructors/$instructorId/assigned-classes/index'
import { Route as ProtectedDepartmentsDepartmentIdEditIndexRouteImport } from './routes/_protected/departments/$departmentId/edit/index'
import { Route as ProtectedCoursesCourseIdEditIndexRouteImport } from './routes/_protected/courses/$courseId/edit/index'
import { Route as ProtectedClassesClassIdEditIndexRouteImport } from './routes/_protected/classes/$classId/edit/index'
import { Route as ProtectedAdminsAdminIdEditIndexRouteImport } from './routes/_protected/admins/$adminId/edit/index'

const UnprotectedRouteRoute = UnprotectedRouteRouteImport.update({
  id: '/_unprotected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnprotectedLoginIndexRoute = UnprotectedLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => UnprotectedRouteRoute,
} as any)
const ProtectedStudentsIndexRoute = ProtectedStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSemestersIndexRoute = ProtectedSemestersIndexRouteImport.update({
  id: '/semesters/',
  path: '/semesters/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSectionsIndexRoute = ProtectedSectionsIndexRouteImport.update({
  id: '/sections/',
  path: '/sections/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProgramsIndexRoute = ProtectedProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedInstructorsIndexRoute =
  ProtectedInstructorsIndexRouteImport.update({
    id: '/instructors/',
    path: '/instructors/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDepartmentsIndexRoute =
  ProtectedDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCoursesIndexRoute = ProtectedCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedClassesIndexRoute = ProtectedClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminsIndexRoute = ProtectedAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStudentsStudentIdRouteRoute =
  ProtectedStudentsStudentIdRouteRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInstructorsInstructorIdRouteRoute =
  ProtectedInstructorsInstructorIdRouteRouteImport.update({
    id: '/instructors/$instructorId',
    path: '/instructors/$instructorId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedStudentsCreateIndexRoute =
  ProtectedStudentsCreateIndexRouteImport.update({
    id: '/students/create/',
    path: '/students/create/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedStudentsStudentIdIndexRoute =
  ProtectedStudentsStudentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedStudentsStudentIdRouteRoute,
  } as any)
const ProtectedSemestersCreateIndexRoute =
  ProtectedSemestersCreateIndexRouteImport.update({
    id: '/semesters/create/',
    path: '/semesters/create/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSectionsCreateIndexRoute =
  ProtectedSectionsCreateIndexRouteImport.update({
    id: '/sections/create/',
    path: '/sections/create/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSectionsSectionIdIndexRoute =
  ProtectedSectionsSectionIdIndexRouteImport.update({
    id: '/sections/$sectionId/',
    path: '/sections/$sectionId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedProgramsCreateIndexRoute =
  ProtectedProgramsCreateIndexRouteImport.update({
    id: '/programs/create/',
    path: '/programs/create/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInstructorsCreateIndexRoute =
  ProtectedInstructorsCreateIndexRouteImport.update({
    id: '/instructors/create/',
    path: '/instructors/create/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInstructorsInstructorIdIndexRoute =
  ProtectedInstructorsInstructorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedInstructorsInstructorIdRouteRoute,
  } as any)
const ProtectedDepartmentsCreateIndexRoute =
  ProtectedDepartmentsCreateIndexRouteImport.update({
    id: '/departments/create/',
    path: '/departments/create/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCoursesCreateIndexRoute =
  ProtectedCoursesCreateIndexRouteImport.update({
    id: '/courses/create/',
    path: '/courses/create/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedClassesCreateIndexRoute =
  ProtectedClassesCreateIndexRouteImport.update({
    id: '/classes/create/',
    path: '/classes/create/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminsCreateIndexRoute =
  ProtectedAdminsCreateIndexRouteImport.update({
    id: '/admins/create/',
    path: '/admins/create/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedStudentsStudentIdEnrollToClassIndexRoute =
  ProtectedStudentsStudentIdEnrollToClassIndexRouteImport.update({
    id: '/students/$studentId_/enroll-to-class/',
    path: '/students/$studentId/enroll-to-class/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedStudentsStudentIdEditIndexRoute =
  ProtectedStudentsStudentIdEditIndexRouteImport.update({
    id: '/students/$studentId_/edit/',
    path: '/students/$studentId/edit/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedStudentsStudentIdEnrolledClassesIndexRoute =
  ProtectedStudentsStudentIdEnrolledClassesIndexRouteImport.update({
    id: '/enrolled-classes/',
    path: '/enrolled-classes/',
    getParentRoute: () => ProtectedStudentsStudentIdRouteRoute,
  } as any)
const ProtectedSectionsSectionIdEditIndexRoute =
  ProtectedSectionsSectionIdEditIndexRouteImport.update({
    id: '/sections/$sectionId/edit/',
    path: '/sections/$sectionId/edit/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedProgramsProgramIdEditIndexRoute =
  ProtectedProgramsProgramIdEditIndexRouteImport.update({
    id: '/programs/$programId/edit/',
    path: '/programs/$programId/edit/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInstructorsInstructorIdEditIndexRoute =
  ProtectedInstructorsInstructorIdEditIndexRouteImport.update({
    id: '/instructors/$instructorId_/edit/',
    path: '/instructors/$instructorId/edit/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInstructorsInstructorIdAssignToClassIndexRoute =
  ProtectedInstructorsInstructorIdAssignToClassIndexRouteImport.update({
    id: '/instructors/$instructorId_/assign-to-class/',
    path: '/instructors/$instructorId/assign-to-class/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInstructorsInstructorIdAssignedClassesIndexRoute =
  ProtectedInstructorsInstructorIdAssignedClassesIndexRouteImport.update({
    id: '/assigned-classes/',
    path: '/assigned-classes/',
    getParentRoute: () => ProtectedInstructorsInstructorIdRouteRoute,
  } as any)
const ProtectedDepartmentsDepartmentIdEditIndexRoute =
  ProtectedDepartmentsDepartmentIdEditIndexRouteImport.update({
    id: '/departments/$departmentId/edit/',
    path: '/departments/$departmentId/edit/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCoursesCourseIdEditIndexRoute =
  ProtectedCoursesCourseIdEditIndexRouteImport.update({
    id: '/courses/$courseId/edit/',
    path: '/courses/$courseId/edit/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedClassesClassIdEditIndexRoute =
  ProtectedClassesClassIdEditIndexRouteImport.update({
    id: '/classes/$classId/edit/',
    path: '/classes/$classId/edit/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminsAdminIdEditIndexRoute =
  ProtectedAdminsAdminIdEditIndexRouteImport.update({
    id: '/admins/$adminId/edit/',
    path: '/admins/$adminId/edit/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instructors/$instructorId': typeof ProtectedInstructorsInstructorIdRouteRouteWithChildren
  '/students/$studentId': typeof ProtectedStudentsStudentIdRouteRouteWithChildren
  '/admins': typeof ProtectedAdminsIndexRoute
  '/classes': typeof ProtectedClassesIndexRoute
  '/courses': typeof ProtectedCoursesIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/departments': typeof ProtectedDepartmentsIndexRoute
  '/instructors': typeof ProtectedInstructorsIndexRoute
  '/programs': typeof ProtectedProgramsIndexRoute
  '/sections': typeof ProtectedSectionsIndexRoute
  '/semesters': typeof ProtectedSemestersIndexRoute
  '/students': typeof ProtectedStudentsIndexRoute
  '/login': typeof UnprotectedLoginIndexRoute
  '/admins/create': typeof ProtectedAdminsCreateIndexRoute
  '/classes/create': typeof ProtectedClassesCreateIndexRoute
  '/courses/create': typeof ProtectedCoursesCreateIndexRoute
  '/departments/create': typeof ProtectedDepartmentsCreateIndexRoute
  '/instructors/$instructorId/': typeof ProtectedInstructorsInstructorIdIndexRoute
  '/instructors/create': typeof ProtectedInstructorsCreateIndexRoute
  '/programs/create': typeof ProtectedProgramsCreateIndexRoute
  '/sections/$sectionId': typeof ProtectedSectionsSectionIdIndexRoute
  '/sections/create': typeof ProtectedSectionsCreateIndexRoute
  '/semesters/create': typeof ProtectedSemestersCreateIndexRoute
  '/students/$studentId/': typeof ProtectedStudentsStudentIdIndexRoute
  '/students/create': typeof ProtectedStudentsCreateIndexRoute
  '/admins/$adminId/edit': typeof ProtectedAdminsAdminIdEditIndexRoute
  '/classes/$classId/edit': typeof ProtectedClassesClassIdEditIndexRoute
  '/courses/$courseId/edit': typeof ProtectedCoursesCourseIdEditIndexRoute
  '/departments/$departmentId/edit': typeof ProtectedDepartmentsDepartmentIdEditIndexRoute
  '/instructors/$instructorId/assigned-classes': typeof ProtectedInstructorsInstructorIdAssignedClassesIndexRoute
  '/instructors/$instructorId/assign-to-class': typeof ProtectedInstructorsInstructorIdAssignToClassIndexRoute
  '/instructors/$instructorId/edit': typeof ProtectedInstructorsInstructorIdEditIndexRoute
  '/programs/$programId/edit': typeof ProtectedProgramsProgramIdEditIndexRoute
  '/sections/$sectionId/edit': typeof ProtectedSectionsSectionIdEditIndexRoute
  '/students/$studentId/enrolled-classes': typeof ProtectedStudentsStudentIdEnrolledClassesIndexRoute
  '/students/$studentId/edit': typeof ProtectedStudentsStudentIdEditIndexRoute
  '/students/$studentId/enroll-to-class': typeof ProtectedStudentsStudentIdEnrollToClassIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof ProtectedAdminsIndexRoute
  '/classes': typeof ProtectedClassesIndexRoute
  '/courses': typeof ProtectedCoursesIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/departments': typeof ProtectedDepartmentsIndexRoute
  '/instructors': typeof ProtectedInstructorsIndexRoute
  '/programs': typeof ProtectedProgramsIndexRoute
  '/sections': typeof ProtectedSectionsIndexRoute
  '/semesters': typeof ProtectedSemestersIndexRoute
  '/students': typeof ProtectedStudentsIndexRoute
  '/login': typeof UnprotectedLoginIndexRoute
  '/admins/create': typeof ProtectedAdminsCreateIndexRoute
  '/classes/create': typeof ProtectedClassesCreateIndexRoute
  '/courses/create': typeof ProtectedCoursesCreateIndexRoute
  '/departments/create': typeof ProtectedDepartmentsCreateIndexRoute
  '/instructors/$instructorId': typeof ProtectedInstructorsInstructorIdIndexRoute
  '/instructors/create': typeof ProtectedInstructorsCreateIndexRoute
  '/programs/create': typeof ProtectedProgramsCreateIndexRoute
  '/sections/$sectionId': typeof ProtectedSectionsSectionIdIndexRoute
  '/sections/create': typeof ProtectedSectionsCreateIndexRoute
  '/semesters/create': typeof ProtectedSemestersCreateIndexRoute
  '/students/$studentId': typeof ProtectedStudentsStudentIdIndexRoute
  '/students/create': typeof ProtectedStudentsCreateIndexRoute
  '/admins/$adminId/edit': typeof ProtectedAdminsAdminIdEditIndexRoute
  '/classes/$classId/edit': typeof ProtectedClassesClassIdEditIndexRoute
  '/courses/$courseId/edit': typeof ProtectedCoursesCourseIdEditIndexRoute
  '/departments/$departmentId/edit': typeof ProtectedDepartmentsDepartmentIdEditIndexRoute
  '/instructors/$instructorId/assigned-classes': typeof ProtectedInstructorsInstructorIdAssignedClassesIndexRoute
  '/instructors/$instructorId/assign-to-class': typeof ProtectedInstructorsInstructorIdAssignToClassIndexRoute
  '/instructors/$instructorId/edit': typeof ProtectedInstructorsInstructorIdEditIndexRoute
  '/programs/$programId/edit': typeof ProtectedProgramsProgramIdEditIndexRoute
  '/sections/$sectionId/edit': typeof ProtectedSectionsSectionIdEditIndexRoute
  '/students/$studentId/enrolled-classes': typeof ProtectedStudentsStudentIdEnrolledClassesIndexRoute
  '/students/$studentId/edit': typeof ProtectedStudentsStudentIdEditIndexRoute
  '/students/$studentId/enroll-to-class': typeof ProtectedStudentsStudentIdEnrollToClassIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_unprotected': typeof UnprotectedRouteRouteWithChildren
  '/_protected/instructors/$instructorId': typeof ProtectedInstructorsInstructorIdRouteRouteWithChildren
  '/_protected/students/$studentId': typeof ProtectedStudentsStudentIdRouteRouteWithChildren
  '/_protected/admins/': typeof ProtectedAdminsIndexRoute
  '/_protected/classes/': typeof ProtectedClassesIndexRoute
  '/_protected/courses/': typeof ProtectedCoursesIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/departments/': typeof ProtectedDepartmentsIndexRoute
  '/_protected/instructors/': typeof ProtectedInstructorsIndexRoute
  '/_protected/programs/': typeof ProtectedProgramsIndexRoute
  '/_protected/sections/': typeof ProtectedSectionsIndexRoute
  '/_protected/semesters/': typeof ProtectedSemestersIndexRoute
  '/_protected/students/': typeof ProtectedStudentsIndexRoute
  '/_unprotected/login/': typeof UnprotectedLoginIndexRoute
  '/_protected/admins/create/': typeof ProtectedAdminsCreateIndexRoute
  '/_protected/classes/create/': typeof ProtectedClassesCreateIndexRoute
  '/_protected/courses/create/': typeof ProtectedCoursesCreateIndexRoute
  '/_protected/departments/create/': typeof ProtectedDepartmentsCreateIndexRoute
  '/_protected/instructors/$instructorId/': typeof ProtectedInstructorsInstructorIdIndexRoute
  '/_protected/instructors/create/': typeof ProtectedInstructorsCreateIndexRoute
  '/_protected/programs/create/': typeof ProtectedProgramsCreateIndexRoute
  '/_protected/sections/$sectionId/': typeof ProtectedSectionsSectionIdIndexRoute
  '/_protected/sections/create/': typeof ProtectedSectionsCreateIndexRoute
  '/_protected/semesters/create/': typeof ProtectedSemestersCreateIndexRoute
  '/_protected/students/$studentId/': typeof ProtectedStudentsStudentIdIndexRoute
  '/_protected/students/create/': typeof ProtectedStudentsCreateIndexRoute
  '/_protected/admins/$adminId/edit/': typeof ProtectedAdminsAdminIdEditIndexRoute
  '/_protected/classes/$classId/edit/': typeof ProtectedClassesClassIdEditIndexRoute
  '/_protected/courses/$courseId/edit/': typeof ProtectedCoursesCourseIdEditIndexRoute
  '/_protected/departments/$departmentId/edit/': typeof ProtectedDepartmentsDepartmentIdEditIndexRoute
  '/_protected/instructors/$instructorId/assigned-classes/': typeof ProtectedInstructorsInstructorIdAssignedClassesIndexRoute
  '/_protected/instructors/$instructorId_/assign-to-class/': typeof ProtectedInstructorsInstructorIdAssignToClassIndexRoute
  '/_protected/instructors/$instructorId_/edit/': typeof ProtectedInstructorsInstructorIdEditIndexRoute
  '/_protected/programs/$programId/edit/': typeof ProtectedProgramsProgramIdEditIndexRoute
  '/_protected/sections/$sectionId/edit/': typeof ProtectedSectionsSectionIdEditIndexRoute
  '/_protected/students/$studentId/enrolled-classes/': typeof ProtectedStudentsStudentIdEnrolledClassesIndexRoute
  '/_protected/students/$studentId_/edit/': typeof ProtectedStudentsStudentIdEditIndexRoute
  '/_protected/students/$studentId_/enroll-to-class/': typeof ProtectedStudentsStudentIdEnrollToClassIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instructors/$instructorId'
    | '/students/$studentId'
    | '/admins'
    | '/classes'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/instructors'
    | '/programs'
    | '/sections'
    | '/semesters'
    | '/students'
    | '/login'
    | '/admins/create'
    | '/classes/create'
    | '/courses/create'
    | '/departments/create'
    | '/instructors/$instructorId/'
    | '/instructors/create'
    | '/programs/create'
    | '/sections/$sectionId'
    | '/sections/create'
    | '/semesters/create'
    | '/students/$studentId/'
    | '/students/create'
    | '/admins/$adminId/edit'
    | '/classes/$classId/edit'
    | '/courses/$courseId/edit'
    | '/departments/$departmentId/edit'
    | '/instructors/$instructorId/assigned-classes'
    | '/instructors/$instructorId/assign-to-class'
    | '/instructors/$instructorId/edit'
    | '/programs/$programId/edit'
    | '/sections/$sectionId/edit'
    | '/students/$studentId/enrolled-classes'
    | '/students/$studentId/edit'
    | '/students/$studentId/enroll-to-class'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/classes'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/instructors'
    | '/programs'
    | '/sections'
    | '/semesters'
    | '/students'
    | '/login'
    | '/admins/create'
    | '/classes/create'
    | '/courses/create'
    | '/departments/create'
    | '/instructors/$instructorId'
    | '/instructors/create'
    | '/programs/create'
    | '/sections/$sectionId'
    | '/sections/create'
    | '/semesters/create'
    | '/students/$studentId'
    | '/students/create'
    | '/admins/$adminId/edit'
    | '/classes/$classId/edit'
    | '/courses/$courseId/edit'
    | '/departments/$departmentId/edit'
    | '/instructors/$instructorId/assigned-classes'
    | '/instructors/$instructorId/assign-to-class'
    | '/instructors/$instructorId/edit'
    | '/programs/$programId/edit'
    | '/sections/$sectionId/edit'
    | '/students/$studentId/enrolled-classes'
    | '/students/$studentId/edit'
    | '/students/$studentId/enroll-to-class'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_unprotected'
    | '/_protected/instructors/$instructorId'
    | '/_protected/students/$studentId'
    | '/_protected/admins/'
    | '/_protected/classes/'
    | '/_protected/courses/'
    | '/_protected/dashboard/'
    | '/_protected/departments/'
    | '/_protected/instructors/'
    | '/_protected/programs/'
    | '/_protected/sections/'
    | '/_protected/semesters/'
    | '/_protected/students/'
    | '/_unprotected/login/'
    | '/_protected/admins/create/'
    | '/_protected/classes/create/'
    | '/_protected/courses/create/'
    | '/_protected/departments/create/'
    | '/_protected/instructors/$instructorId/'
    | '/_protected/instructors/create/'
    | '/_protected/programs/create/'
    | '/_protected/sections/$sectionId/'
    | '/_protected/sections/create/'
    | '/_protected/semesters/create/'
    | '/_protected/students/$studentId/'
    | '/_protected/students/create/'
    | '/_protected/admins/$adminId/edit/'
    | '/_protected/classes/$classId/edit/'
    | '/_protected/courses/$courseId/edit/'
    | '/_protected/departments/$departmentId/edit/'
    | '/_protected/instructors/$instructorId/assigned-classes/'
    | '/_protected/instructors/$instructorId_/assign-to-class/'
    | '/_protected/instructors/$instructorId_/edit/'
    | '/_protected/programs/$programId/edit/'
    | '/_protected/sections/$sectionId/edit/'
    | '/_protected/students/$studentId/enrolled-classes/'
    | '/_protected/students/$studentId_/edit/'
    | '/_protected/students/$studentId_/enroll-to-class/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  UnprotectedRouteRoute: typeof UnprotectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unprotected': {
      id: '/_unprotected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnprotectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unprotected/login/': {
      id: '/_unprotected/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnprotectedLoginIndexRouteImport
      parentRoute: typeof UnprotectedRouteRoute
    }
    '/_protected/students/': {
      id: '/_protected/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof ProtectedStudentsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/semesters/': {
      id: '/_protected/semesters/'
      path: '/semesters'
      fullPath: '/semesters'
      preLoaderRoute: typeof ProtectedSemestersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sections/': {
      id: '/_protected/sections/'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof ProtectedSectionsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/programs/': {
      id: '/_protected/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProtectedProgramsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/instructors/': {
      id: '/_protected/instructors/'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof ProtectedInstructorsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/departments/': {
      id: '/_protected/departments/'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof ProtectedDepartmentsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/courses/': {
      id: '/_protected/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof ProtectedCoursesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/classes/': {
      id: '/_protected/classes/'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ProtectedClassesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admins/': {
      id: '/_protected/admins/'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof ProtectedAdminsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/students/$studentId': {
      id: '/_protected/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof ProtectedStudentsStudentIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/instructors/$instructorId': {
      id: '/_protected/instructors/$instructorId'
      path: '/instructors/$instructorId'
      fullPath: '/instructors/$instructorId'
      preLoaderRoute: typeof ProtectedInstructorsInstructorIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/students/create/': {
      id: '/_protected/students/create/'
      path: '/students/create'
      fullPath: '/students/create'
      preLoaderRoute: typeof ProtectedStudentsCreateIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/students/$studentId/': {
      id: '/_protected/students/$studentId/'
      path: '/'
      fullPath: '/students/$studentId/'
      preLoaderRoute: typeof ProtectedStudentsStudentIdIndexRouteImport
      parentRoute: typeof ProtectedStudentsStudentIdRouteRoute
    }
    '/_protected/semesters/create/': {
      id: '/_protected/semesters/create/'
      path: '/semesters/create'
      fullPath: '/semesters/create'
      preLoaderRoute: typeof ProtectedSemestersCreateIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sections/create/': {
      id: '/_protected/sections/create/'
      path: '/sections/create'
      fullPath: '/sections/create'
      preLoaderRoute: typeof ProtectedSectionsCreateIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sections/$sectionId/': {
      id: '/_protected/sections/$sectionId/'
      path: '/sections/$sectionId'
      fullPath: '/sections/$sectionId'
      preLoaderRoute: typeof ProtectedSectionsSectionIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/programs/create/': {
      id: '/_protected/programs/create/'
      path: '/programs/create'
      fullPath: '/programs/create'
      preLoaderRoute: typeof ProtectedProgramsCreateIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/instructors/create/': {
      id: '/_protected/instructors/create/'
      path: '/instructors/create'
      fullPath: '/instructors/create'
      preLoaderRoute: typeof ProtectedInstructorsCreateIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/instructors/$instructorId/': {
      id: '/_protected/instructors/$instructorId/'
      path: '/'
      fullPath: '/instructors/$instructorId/'
      preLoaderRoute: typeof ProtectedInstructorsInstructorIdIndexRouteImport
      parentRoute: typeof ProtectedInstructorsInstructorIdRouteRoute
    }
    '/_protected/departments/create/': {
      id: '/_protected/departments/create/'
      path: '/departments/create'
      fullPath: '/departments/create'
      preLoaderRoute: typeof ProtectedDepartmentsCreateIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/courses/create/': {
      id: '/_protected/courses/create/'
      path: '/courses/create'
      fullPath: '/courses/create'
      preLoaderRoute: typeof ProtectedCoursesCreateIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/classes/create/': {
      id: '/_protected/classes/create/'
      path: '/classes/create'
      fullPath: '/classes/create'
      preLoaderRoute: typeof ProtectedClassesCreateIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admins/create/': {
      id: '/_protected/admins/create/'
      path: '/admins/create'
      fullPath: '/admins/create'
      preLoaderRoute: typeof ProtectedAdminsCreateIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/students/$studentId_/enroll-to-class/': {
      id: '/_protected/students/$studentId_/enroll-to-class/'
      path: '/students/$studentId/enroll-to-class'
      fullPath: '/students/$studentId/enroll-to-class'
      preLoaderRoute: typeof ProtectedStudentsStudentIdEnrollToClassIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/students/$studentId_/edit/': {
      id: '/_protected/students/$studentId_/edit/'
      path: '/students/$studentId/edit'
      fullPath: '/students/$studentId/edit'
      preLoaderRoute: typeof ProtectedStudentsStudentIdEditIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/students/$studentId/enrolled-classes/': {
      id: '/_protected/students/$studentId/enrolled-classes/'
      path: '/enrolled-classes'
      fullPath: '/students/$studentId/enrolled-classes'
      preLoaderRoute: typeof ProtectedStudentsStudentIdEnrolledClassesIndexRouteImport
      parentRoute: typeof ProtectedStudentsStudentIdRouteRoute
    }
    '/_protected/sections/$sectionId/edit/': {
      id: '/_protected/sections/$sectionId/edit/'
      path: '/sections/$sectionId/edit'
      fullPath: '/sections/$sectionId/edit'
      preLoaderRoute: typeof ProtectedSectionsSectionIdEditIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/programs/$programId/edit/': {
      id: '/_protected/programs/$programId/edit/'
      path: '/programs/$programId/edit'
      fullPath: '/programs/$programId/edit'
      preLoaderRoute: typeof ProtectedProgramsProgramIdEditIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/instructors/$instructorId_/edit/': {
      id: '/_protected/instructors/$instructorId_/edit/'
      path: '/instructors/$instructorId/edit'
      fullPath: '/instructors/$instructorId/edit'
      preLoaderRoute: typeof ProtectedInstructorsInstructorIdEditIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/instructors/$instructorId_/assign-to-class/': {
      id: '/_protected/instructors/$instructorId_/assign-to-class/'
      path: '/instructors/$instructorId/assign-to-class'
      fullPath: '/instructors/$instructorId/assign-to-class'
      preLoaderRoute: typeof ProtectedInstructorsInstructorIdAssignToClassIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/instructors/$instructorId/assigned-classes/': {
      id: '/_protected/instructors/$instructorId/assigned-classes/'
      path: '/assigned-classes'
      fullPath: '/instructors/$instructorId/assigned-classes'
      preLoaderRoute: typeof ProtectedInstructorsInstructorIdAssignedClassesIndexRouteImport
      parentRoute: typeof ProtectedInstructorsInstructorIdRouteRoute
    }
    '/_protected/departments/$departmentId/edit/': {
      id: '/_protected/departments/$departmentId/edit/'
      path: '/departments/$departmentId/edit'
      fullPath: '/departments/$departmentId/edit'
      preLoaderRoute: typeof ProtectedDepartmentsDepartmentIdEditIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/courses/$courseId/edit/': {
      id: '/_protected/courses/$courseId/edit/'
      path: '/courses/$courseId/edit'
      fullPath: '/courses/$courseId/edit'
      preLoaderRoute: typeof ProtectedCoursesCourseIdEditIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/classes/$classId/edit/': {
      id: '/_protected/classes/$classId/edit/'
      path: '/classes/$classId/edit'
      fullPath: '/classes/$classId/edit'
      preLoaderRoute: typeof ProtectedClassesClassIdEditIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admins/$adminId/edit/': {
      id: '/_protected/admins/$adminId/edit/'
      path: '/admins/$adminId/edit'
      fullPath: '/admins/$adminId/edit'
      preLoaderRoute: typeof ProtectedAdminsAdminIdEditIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedInstructorsInstructorIdRouteRouteChildren {
  ProtectedInstructorsInstructorIdIndexRoute: typeof ProtectedInstructorsInstructorIdIndexRoute
  ProtectedInstructorsInstructorIdAssignedClassesIndexRoute: typeof ProtectedInstructorsInstructorIdAssignedClassesIndexRoute
}

const ProtectedInstructorsInstructorIdRouteRouteChildren: ProtectedInstructorsInstructorIdRouteRouteChildren =
  {
    ProtectedInstructorsInstructorIdIndexRoute:
      ProtectedInstructorsInstructorIdIndexRoute,
    ProtectedInstructorsInstructorIdAssignedClassesIndexRoute:
      ProtectedInstructorsInstructorIdAssignedClassesIndexRoute,
  }

const ProtectedInstructorsInstructorIdRouteRouteWithChildren =
  ProtectedInstructorsInstructorIdRouteRoute._addFileChildren(
    ProtectedInstructorsInstructorIdRouteRouteChildren,
  )

interface ProtectedStudentsStudentIdRouteRouteChildren {
  ProtectedStudentsStudentIdIndexRoute: typeof ProtectedStudentsStudentIdIndexRoute
  ProtectedStudentsStudentIdEnrolledClassesIndexRoute: typeof ProtectedStudentsStudentIdEnrolledClassesIndexRoute
}

const ProtectedStudentsStudentIdRouteRouteChildren: ProtectedStudentsStudentIdRouteRouteChildren =
  {
    ProtectedStudentsStudentIdIndexRoute: ProtectedStudentsStudentIdIndexRoute,
    ProtectedStudentsStudentIdEnrolledClassesIndexRoute:
      ProtectedStudentsStudentIdEnrolledClassesIndexRoute,
  }

const ProtectedStudentsStudentIdRouteRouteWithChildren =
  ProtectedStudentsStudentIdRouteRoute._addFileChildren(
    ProtectedStudentsStudentIdRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedInstructorsInstructorIdRouteRoute: typeof ProtectedInstructorsInstructorIdRouteRouteWithChildren
  ProtectedStudentsStudentIdRouteRoute: typeof ProtectedStudentsStudentIdRouteRouteWithChildren
  ProtectedAdminsIndexRoute: typeof ProtectedAdminsIndexRoute
  ProtectedClassesIndexRoute: typeof ProtectedClassesIndexRoute
  ProtectedCoursesIndexRoute: typeof ProtectedCoursesIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDepartmentsIndexRoute: typeof ProtectedDepartmentsIndexRoute
  ProtectedInstructorsIndexRoute: typeof ProtectedInstructorsIndexRoute
  ProtectedProgramsIndexRoute: typeof ProtectedProgramsIndexRoute
  ProtectedSectionsIndexRoute: typeof ProtectedSectionsIndexRoute
  ProtectedSemestersIndexRoute: typeof ProtectedSemestersIndexRoute
  ProtectedStudentsIndexRoute: typeof ProtectedStudentsIndexRoute
  ProtectedAdminsCreateIndexRoute: typeof ProtectedAdminsCreateIndexRoute
  ProtectedClassesCreateIndexRoute: typeof ProtectedClassesCreateIndexRoute
  ProtectedCoursesCreateIndexRoute: typeof ProtectedCoursesCreateIndexRoute
  ProtectedDepartmentsCreateIndexRoute: typeof ProtectedDepartmentsCreateIndexRoute
  ProtectedInstructorsCreateIndexRoute: typeof ProtectedInstructorsCreateIndexRoute
  ProtectedProgramsCreateIndexRoute: typeof ProtectedProgramsCreateIndexRoute
  ProtectedSectionsSectionIdIndexRoute: typeof ProtectedSectionsSectionIdIndexRoute
  ProtectedSectionsCreateIndexRoute: typeof ProtectedSectionsCreateIndexRoute
  ProtectedSemestersCreateIndexRoute: typeof ProtectedSemestersCreateIndexRoute
  ProtectedStudentsCreateIndexRoute: typeof ProtectedStudentsCreateIndexRoute
  ProtectedAdminsAdminIdEditIndexRoute: typeof ProtectedAdminsAdminIdEditIndexRoute
  ProtectedClassesClassIdEditIndexRoute: typeof ProtectedClassesClassIdEditIndexRoute
  ProtectedCoursesCourseIdEditIndexRoute: typeof ProtectedCoursesCourseIdEditIndexRoute
  ProtectedDepartmentsDepartmentIdEditIndexRoute: typeof ProtectedDepartmentsDepartmentIdEditIndexRoute
  ProtectedInstructorsInstructorIdAssignToClassIndexRoute: typeof ProtectedInstructorsInstructorIdAssignToClassIndexRoute
  ProtectedInstructorsInstructorIdEditIndexRoute: typeof ProtectedInstructorsInstructorIdEditIndexRoute
  ProtectedProgramsProgramIdEditIndexRoute: typeof ProtectedProgramsProgramIdEditIndexRoute
  ProtectedSectionsSectionIdEditIndexRoute: typeof ProtectedSectionsSectionIdEditIndexRoute
  ProtectedStudentsStudentIdEditIndexRoute: typeof ProtectedStudentsStudentIdEditIndexRoute
  ProtectedStudentsStudentIdEnrollToClassIndexRoute: typeof ProtectedStudentsStudentIdEnrollToClassIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedInstructorsInstructorIdRouteRoute:
    ProtectedInstructorsInstructorIdRouteRouteWithChildren,
  ProtectedStudentsStudentIdRouteRoute:
    ProtectedStudentsStudentIdRouteRouteWithChildren,
  ProtectedAdminsIndexRoute: ProtectedAdminsIndexRoute,
  ProtectedClassesIndexRoute: ProtectedClassesIndexRoute,
  ProtectedCoursesIndexRoute: ProtectedCoursesIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDepartmentsIndexRoute: ProtectedDepartmentsIndexRoute,
  ProtectedInstructorsIndexRoute: ProtectedInstructorsIndexRoute,
  ProtectedProgramsIndexRoute: ProtectedProgramsIndexRoute,
  ProtectedSectionsIndexRoute: ProtectedSectionsIndexRoute,
  ProtectedSemestersIndexRoute: ProtectedSemestersIndexRoute,
  ProtectedStudentsIndexRoute: ProtectedStudentsIndexRoute,
  ProtectedAdminsCreateIndexRoute: ProtectedAdminsCreateIndexRoute,
  ProtectedClassesCreateIndexRoute: ProtectedClassesCreateIndexRoute,
  ProtectedCoursesCreateIndexRoute: ProtectedCoursesCreateIndexRoute,
  ProtectedDepartmentsCreateIndexRoute: ProtectedDepartmentsCreateIndexRoute,
  ProtectedInstructorsCreateIndexRoute: ProtectedInstructorsCreateIndexRoute,
  ProtectedProgramsCreateIndexRoute: ProtectedProgramsCreateIndexRoute,
  ProtectedSectionsSectionIdIndexRoute: ProtectedSectionsSectionIdIndexRoute,
  ProtectedSectionsCreateIndexRoute: ProtectedSectionsCreateIndexRoute,
  ProtectedSemestersCreateIndexRoute: ProtectedSemestersCreateIndexRoute,
  ProtectedStudentsCreateIndexRoute: ProtectedStudentsCreateIndexRoute,
  ProtectedAdminsAdminIdEditIndexRoute: ProtectedAdminsAdminIdEditIndexRoute,
  ProtectedClassesClassIdEditIndexRoute: ProtectedClassesClassIdEditIndexRoute,
  ProtectedCoursesCourseIdEditIndexRoute:
    ProtectedCoursesCourseIdEditIndexRoute,
  ProtectedDepartmentsDepartmentIdEditIndexRoute:
    ProtectedDepartmentsDepartmentIdEditIndexRoute,
  ProtectedInstructorsInstructorIdAssignToClassIndexRoute:
    ProtectedInstructorsInstructorIdAssignToClassIndexRoute,
  ProtectedInstructorsInstructorIdEditIndexRoute:
    ProtectedInstructorsInstructorIdEditIndexRoute,
  ProtectedProgramsProgramIdEditIndexRoute:
    ProtectedProgramsProgramIdEditIndexRoute,
  ProtectedSectionsSectionIdEditIndexRoute:
    ProtectedSectionsSectionIdEditIndexRoute,
  ProtectedStudentsStudentIdEditIndexRoute:
    ProtectedStudentsStudentIdEditIndexRoute,
  ProtectedStudentsStudentIdEnrollToClassIndexRoute:
    ProtectedStudentsStudentIdEnrollToClassIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface UnprotectedRouteRouteChildren {
  UnprotectedLoginIndexRoute: typeof UnprotectedLoginIndexRoute
}

const UnprotectedRouteRouteChildren: UnprotectedRouteRouteChildren = {
  UnprotectedLoginIndexRoute: UnprotectedLoginIndexRoute,
}

const UnprotectedRouteRouteWithChildren =
  UnprotectedRouteRoute._addFileChildren(UnprotectedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  UnprotectedRouteRoute: UnprotectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
